sudo: required

services:
  - docker

install:
  - docker build -t "$DOCKERHUB_REPO" .
  
script:
  - echo "==> Validating build"
  # - docker run -d --name container-test1 $DOCKERHUB_REPO bash
  - docker run -d --name container-test1 $DOCKERHUB_REPO
  - docker exec -i container-test1 "ansible-playbook --version" > result-ubuntu
  - docker container ls 
  - sh -c "[ -s result-ubuntu ]"
  - if [ $TRAVIS_TEST_RESULT -eq 0 ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push $DOCKERHUB_REPO; fi

notifications:
  email: false
  slack:
    rooms:
      - secure: YsF4TUcVHhY9pmJoBE0Jwf6MHeY8UV/Ru76/zj0chTyba/AP/+kT1ptxPo/IVJZU94hBaSZvNtuUYGuCSh4Eti1B68eI9GJqaKmbiMKn96RtlSFnWi4ZNnwbGmSc3Nd8zAoQBVkDdPs1HOFeNIpXtYPErJyH0E4YIPpVpzGXDWb2YWJcxkW29Erm5ggECwM8sz+0W9+CPFmSzCVUIupSZ1iqIrSg1rqbtXGuYVN+9J9T0QDT0psOAdZzBdyzPzTWlTBB1lGGv4sSWRDAqzzE3Kdstk51LyuZq3okWoAu6j6hF8wsdu17N3qPGuC+HudcmwiyhbWzbs7JR2hlANXQeQZQz2TdUuVo2YbCbPow6pOsFuAb79cajNp7FlUpIu7UMg7bsy/Z6G5x3mHfQGxBTPVjl4Dx9IE6nkoCNKlaH7ps8EelsUx6t5tUlPhxb/zHEH1AkDAwZa7zlHCMQMoEPMwYR8knc6n7dT3XO59BLNubJU4++SEzu6GP045V6FX5IR6v+HzSFCBzzIm9/x2Bx1SsWtE43GYRZRrgXn4PAOpMWW5zhR6chjeDfa4bmYG1TzxhVEr1vvIyZ+3AnkVBgxnc1yR0vegz1iEEsc9P/VpnZy9WU41s+pkkFJIBPDCYds6ikfXJ0+TaWDdQN40NehDy7K7ue0TZVpJLaoLt+rU=
      - secure: m69ZF8kLPXUE4mGwPisI9/Mo+kwqZkeDuaDwedtklJIJrU2csWuqByAQKUqmKwnLwsEhYJy8bzNVtvrWwVN2lEdkq6p9uymz/cN4opBwJxjf9Yjab4AwnuZCQ7iO7rJEYg3rqe9JoFV9bAcUCZel6X2A5zeuzyrgX9hVDuTkmC0/MVStSY3JwXDCprrv8rmzYwtaNe9SzZtJ5buQdWwCP4uwDLeDd6gkc+km6HmAS0zHwEyeBWe6uGIcWJtgt+tjmUpbZiMnIm4bla9haGeiXNkPBOnzeN0+SBTWCnKjtF1FgoFCg/gGvlpwQNZkH6DKaNJQbrw9iKhLQSHaJRpJQx478APsomHXrMZkilum8D74r8rT+pBe5SEgeI39AKOPgxKnLb0PMPlw3i+SDIIsuYOmWF7zGTys0mPkf+Nmtpe1XiUr5ztQKca8ugL2L/4p/ANz4qyHUhrm54kDVcJVzmERtfuSQail1pdo/e1IGNwgCX/e3NgHIhFQPRCMTxUcS1HkrHmURGqsIvNPLwvfAa1eqYso2pxVxc+tx96KZDkCED3uIcoDF4EZWn8C9wRb5AnYlA2S94+8CHCsVu7uBfJD21ktu4kXAsqpb2+f9Err8b27EL6jGTg+Dp7SoBz7eItdx3bAWg4AFOnLSFsBKhSZdmOX7ZujjMt+w2iFRJU=
#    template:
#      - "%{repository_slug} (%{commit}) : %{message} %{foo} "
#      - "Build details: %{build_url}"

# after_success:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker push $DOCKERHUB_REPO
